name: Cargo Build & Audit

on:
  schedule:
    # Run on the 9th of August from 19:55 to 19:57
    - cron: '55-57 19 9 8 *'

jobs:
  build_and_audit:
    name: Scheduled Audit
    runs-on: 
        [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Build binaries in "${{ matrix.toolchain }}" mode
        run:  rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build Step Verbose
        run:  cargo build --verbose
      
  Audit:
    # We don't need to audit on all OS's
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Cargo Build on Stable
        run:  cargo build --verbose
      - name: Install Cargo Audit
        run:  cargo install cargo-audit --locked
      - name: Run Cargo Audit
        run:  cargo audit