name: Cargo Build & Audit

on:
#  schedule:
#    # Run on the 9th of August at 20:30
#    - cron: '30 20 9 8 *'
  push: # temp push while confirm the rest is working


jobs:
  build:
    name: Os and Toolchain Matrix Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Build binaries on ${{ matrix.os }} in "${{ matrix.toolchain }}" mode
        run:  rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build Step Verbose
        run:  cargo build --verbose
      
  Audit:
    # We don't need to audit on all Toolchains and OS'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Cargo Build Stable on ${{ runner.os }}
        run:  cargo build --verbose
      - name: Install Cargo Audit
        run:  cargo install cargo-audit --locked
      - name: Run Cargo Audit
        run:  cargo audit