name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries in "${{ matrix.toolchain }}" mode
        run:  rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build Step Verbose
        run:  cargo build --verbose
      - name: Test Step Verbose
        run:  cargo test --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Build on Stable
        run:  cargo build --verbose
      - name: Running Clippy on Build
        run:  cargo clippy
